[mypy]
python_version = 3.13
warn_return_any = true
warn_unused_ignores = true
warn_redundant_casts = true
disallow_untyped_defs = false
ignore_missing_imports = true

exclude = (?x)(
    \.venv/
    | __pycache__/
    | scripts/
    | tests/
)
